### ISSUE TITLE
[BUG] 컴포넌트 현재 그라데이션 안되는 버그, 눌렀을 때 하단부분이 안따라오는 버그

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#51]
**버그 설명**
이미지 참조

**버그 상황 묘사**

**의도한 상황 묘사**
제대로 따라와야 하고, 그라데이션이 책의 하단 색상에 맞춰서 되어야 함. 색상조합 함수 필요할듯?

**스크린샷**
![KakaoTalk_20240909_154615563](https://github.com/user-attachments/assets/514d7a5f-9479-4270-8db4-c09d74db56fb)

**환경**
- 기기
  - [ ] PC
  - [x] Mobile
- 브라우저
  - [x] 크롬
  - [ ] 사파리
  - [ ] 삼성익스플로러

**추가 안내사항**

**Comment by onetuks** [comment]
재현 안 되는딩?
재확인 필요
