### ISSUE TITLE
[BUG] 서평 작성 한번만 했음에도 목록에는 두번만 뜨는 버그?

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#55]
**버그 설명**
상기 동일

**버그 상황 묘사**
1. 서평 등록
2. 서평 등록은 정상적으로 완료, 허나 나의 서재에서 확인시 서평 중복 발생

**의도한 상황 묘사**
하나만 떠야함

(수정) 현재는 애초에 두개가 등록된 것으로 생각되는데, 마이페이지에서는 서평이 1개로 뜸. 피드에도 두개 뜨고 목록에도 두개가 뜨지만 마이페이지에서는 한개임. 실제로 db에서도 한개인지 확인 필요한듯.

**스크린샷**
![KakaoTalk_20240911_180739543_01](https://github.com/user-attachments/assets/d1732167-729a-4e07-8e51-fcd89fcef010)

**환경**
- 기기
  - [ ] PC
  - [x] Mobile
- 브라우저
  - [x] 크롬
  - [ ] 사파리
  - [ ] 삼성익스플로러

**추가 안내사항**

**Comment by onetuks** [comment]
DB에 똑같은 서평 두 개 있음.
아마 1초 차이로 등록된 것을 보니, 아마 화면쪽에서 새로고침을 했거나 하는 특정 상황이 있었을듯
재현되면 다시 리포팅 바람.
