### ISSUE TITLE
[BUG] 서평 전환 버그?

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#56]
**버그 설명**
최신 서평 상태에서, 베스트 서평으로 넘어간 후 최신 서평으로 간다면 아예 안보이는 버그

**버그 상황 묘사**
1. 피드에서 최신 서평 상태임
2. 베스트 서평으로 넘어감
3. 다시 최신서평으로 가면
4. 아예 서평이 안보임

(수정)
현재는 잘 됨. 그런데 이상한 건 당시에는 안됐다는 건데, 서버 반영이 늦은 건지 당초 원인이 뭐였는지 확인이 안됨.

**의도한 상황 묘사**
서평이 보여야함

**스크린샷**
![KakaoTalk_20240911_180739543_02](https://github.com/user-attachments/assets/3218e6ad-e914-431c-a6ad-a094e4bf2ac9)
![KakaoTalk_20240911_180739543_03](https://github.com/user-attachments/assets/7aebb313-4296-49f9-b4cf-c549b21e5832)
![KakaoTalk_20240911_180739543_04](https://github.com/user-attachments/assets/3a57b911-0cdc-49e5-86eb-aa3fb792dbd6)

**환경**
- 기기
  - [ ] PC
  - [x] Mobile
- 브라우저
  - [x] 크롬
  - [ ] 사파리
  - [ ] 삼성익스플로러

**추가 안내사항**

**Comment by onetuks** [comment]
캐시 땜에 그럼 수정할게용
