### ISSUE TITLE
[BUG] 피드카드 밑 수정하기, 삭제하기가 제대로 표시되지 않는 문제

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#57]
**버그 설명**
상기 동일, 정확히는 모바일에서 밑으로 땡겨야 겨우 수정하기와 삭제하기가 제대로 나옴. 손에서 떼는 즉시 수정하기와 삭제하기는 밑으로 들어가버림. 그래서 사실상 클릭 불가능.

**버그 상황 묘사**

**의도한 상황 묘사**
제대로 동작했을때의 상황 묘사

**스크린샷**
![KakaoTalk_20240911_184212732](https://github.com/user-attachments/assets/6b3609c5-6bf1-47b6-ba59-47d605af0b61)
![KakaoTalk_20240911_184212732_01](https://github.com/user-attachments/assets/29e2514a-d91e-4480-8270-eda8821100e5)

**환경**
- 기기
  - [ ] PC
  - [x] Mobile
- 브라우저
  - [x] 크롬
  - [ ] 사파리
  - [ ] 삼성익스플로러

**추가 안내사항**

**Comment by onetuks** [comment]
이런게 이제 픽셀 깎는거임
수정하기랑 삭제하기 버튼 밑에 마진값을 주면 해결됨
