### ISSUE TITLE
[BUG] 프로필 수정 이후 수정 반영 안되면서, 출석체크 중복으로 가능한 문제

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#61]
**버그 설명**
 프로필 수정 이후 수정 반영 안되면서, 출석체크 중복으로 가능한 문제

**버그 상황 묘사**
1. 배경사진, 프로필 사진등을 정상적으로 등록(인스타는 등록하지 않음)
2. 수정하기 누르면 작동하지 않고, 페이지에서 벗어나지지 않음.
3. 이후 강제로 페이지에서 벗어나면 잠깐동안 공란 페이지, 이후 페이지가 등장하면 수정사항 반영이 안됨.
4. 또한 출석체크가 중복으로 됨.

(수정) 출석체크 버그는 별개인듯. 누르면 1회만 가능하다고 뜨는데 실제로는 포인트 적립됨. 

**의도한 상황 묘사**
출첵 중복 안되어야 하고, 수정하기가 정상 반영된다면 수정 되었습니다! 라고 떠야할 듯.

**스크린샷**
![KakaoTalk_20240912_153515297](https://github.com/user-attachments/assets/80a62497-4724-4d9d-b469-2ef979020e18)
![KakaoTalk_20240912_153515297_01](https://github.com/user-attachments/assets/bdf689f7-7374-475f-8d92-3d7ec3b5416d)
![KakaoTalk_20240912_153515297_02](https://github.com/user-attachments/assets/27346832-a09c-4492-aa09-9ad83ff22b44)

**환경**
- 기기
  - [ ] PC
  - [x] Mobile
- 브라우저
  - [x] 크롬
  - [ ] 사파리
  - [ ] 삼성익스플로러

**추가 안내사항**

**Comment by MIchaeL208099** [comment]
확인해보니 날짜랑 상관없이 출첵 되는거 같은데여 3일 연속 출석 뜸

**Comment by onetuks** [comment]
출석 체크 버그는 서버측 이슈로 이관
